website:
  title: Feedback Website
  description: Use this website to provide feedback.

postgres:
  database: feedback-db
  user: feedback-user
  passkey: feedback-password
  host: localhost
  port: 5432

admin:
  username: admin
  passkey: CHANGE_ME_OR_ELSE
